const MAIN_BRAND_COLOR = "#b92f2c";
const MAIN_TEXT_COLOR = "#000000";
const PRIMARY_TEXT_COLOR = "#ffffff";
const MODAL_TEXT_COLOR = "#8c8c8c";
const MAIN_BACKGROUND_COLOR = "#ffffff";
const PRIMARY_BACKGROUND_COLOR = "#000000";
const FOOTER_BACKGROUND_COLOR = "#f7f7f7";
const FOOTER_TEXT_COLOR = "#545454";
const TABLET_BREAKING_POINT = 768;
const DESKTOP_BREAKING_POINT = 1280;

export {
  MAIN_BRAND_COLOR,
  TABLET_BREAKING_POINT,
  DESKTOP_BREAKING_POINT,
  MAIN_TEXT_COLOR,
  FOOTER_BACKGROUND_COLOR,
  FOOTER_TEXT_COLOR,
  MAIN_BACKGROUND_COLOR,
  PRIMARY_TEXT_COLOR,
  PRIMARY_BACKGROUND_COLOR,
  MODAL_TEXT_COLOR
};
